---
- hosts: all
  become: true
  tasks:

  - name: install updates
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
  
  - name: install support for php
    apt:
      name: libapache2-mod-php
      state: latest
